apiVersion: v1
kind: Service
metadata:
  name: fiap-pagamentos-api-service
  namespace: fiap-pagamentos-api

spec:
  type: LoadBalancer
  selector:
    app: fiap-pagamentos-api-deployment
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003